snc_redis:
    clients:
        user:
            type: phpredis
            dsn: "%env(REDIS_URL)%"
            options:
                prefix: "user:"

when@test:
    snc_redis:
        clients:
            user:
                options:
                    prefix: "test_user:"
