services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            bool $debug: '%kernel.debug%'
            Redis $userRedisClient : '@snc_redis.user'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\LoginListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\OpenApi\AuthenticationDecorator:
        decorates: 'api_platform.openapi.factory'
        autoconfigure: false

    App\State\UserRegistrationProcessor:
        bind:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'
